use_frameworks!

target 'YoutubeEngine_Example' do
  pod 'YoutubeEngine', :path => '../'
  pod 'Kingfisher', '~> 3.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'ReactiveSwift', '~> 1.0'

  target 'YoutubeEngine_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10'
    pod 'Nimble', '~> 5.0'
    pod 'OHHTTPStubs/NSURLSession'
    pod 'OHHTTPStubs/Swift'
  end
end
