use_frameworks!

target 'YoutubeEngine_Example' do
  pod 'YoutubeEngine', :path => '../'
  pod 'Kingfisher'
  pod 'Rex'
  pod 'Reusable'

  target 'YoutubeEngine_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
    pod 'Mockingjay'
  end
end
